sudo: required
services:
  - docker

before_install: 
  - docker build -t marcogonca96/docker-react -f Dockerfile.dev .

script:
  - docker run marcogonca96/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-native" 
  end: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-170074378006"
  bucket_path: "react-native"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
